name: Publish

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check OIDC env
        run: |
          echo "OIDC URL set: ${ACTIONS_ID_TOKEN_REQUEST_URL:+YES}"
          echo "OIDC TOKEN set: ${ACTIONS_ID_TOKEN_REQUEST_TOKEN:+YES}"
          echo "npm version: $(npm --version)"
          echo "node version: $(node --version)"

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Publish
        run: npm publish --provenance --access public
        env:
          RELEASE_MODE: 'true'
